### ISSUE TITLE
Default eslint config

### ISSUE THREAD

**Issue by Cellule** [eslint/eslint-tester#19]
I would like to add an option to set the parser to use in the tester.
Right now, https://github.com/eslint/eslint-tester/pull/18 handles the case for specifying a parser per test case. However, it would be nice to be able to run the same test suite with a different parser.

I have two ideas.
- Set the parser when instantiating an ESLintTester.
  
this would mean adding a second parameter to the constructor like 
```js
function ESLintTester(eslint, defaultConfig) {
  ...
  this.defaultConfig = defaultConfig || {};
  this.defaultConfig.rules = this.defaultConfig.rules || {};
}
...
function runRuleForItem(ruleName, item) {
  // use any prefered merge technique, I tend to like lodash.merge.
  var config = merge(this.defaultConfig, item.config);
  // continue as usual
}
```
Then you could do `var eslintTester = new ESLintTester(eslint, {parser: "Esprima"});`

- My second idea is to allow to highjack the defaultConfig altogether of the tester. This would allow to run exactly the same tests with a completely different parser. It should of course be used wisely otherwise you could end up with rules being run with different parser when not wanted.
Anyway, the idea is to provide the option.
You could combine this with my first idea like 
```js
function ESLintTester(eslint, defaultConfig) {
  ...
  // use any prefered merge technique, I tend to like lodash.merge.
  this.defaultConfig = merge(ESLintTester.defaultConfig, defaultConfig) || {};
  this.defaultConfig.rules = this.defaultConfig.rules || {};
}
ESLintTester.defaultConfig = { rules: {} };
...
function runRuleForItem(ruleName, item) {
  // use any prefered merge technique, I tend to like lodash.merge.
  // The merge with ESLintTester.defaultConfig could be done here if 
  // we want to allow it to change between test cases (which I doubt would happen)
  var config = merge(this.defaultConfig, item.config);
  // continue as usual
}
```
Then you could do 
```js
var ESLintTester = require("eslint-tester"); 
ESLintTester.defaultConfig = {
  parser: "Esprima",
  // any other configuration you see fit
};
```

As you saw, this would mean adding/replacing a field on a test case item to have a possible config. instead of having to manually support every configuration we want. This would be completely flexible and allow any and all configuration to passed to the test. 

Another possibility is to simply take everything from the test case that we don't "know" and pass it as configuration for the test. 
```js
function runRuleForItem(ruleName, item) {
  var itemConfig = _.omit(item, ["code", "filename", "global", "globals", "options"]);
  // merge config with default.
  ...
}
```
see [lodash omit](https://lodash.com/docs#omit) for description

With both ideas, you would have configuration dependencies like `Global config <= Tester config <= Test case config`

**Comment by nzakas** [comment]
You're talking a lot about implementation, but not a lot about what you're trying to do. Can you explain the use case you're trying to address?

**Comment by Cellule** [comment]
I want to take a test suite already written and change the parser used without touching any test cases.
Basically I want to run the ESLint test suite with another parser.

But I thought that while I'm at it, I could expand my original thought to cover any and all cases regarding the ESLint config within the test runner.

**Comment by nzakas** [comment]
What I'm asking is, is this a hypothetical desire? Or are you working on a project where you want to do this? I'm trying to understand an exact situation where this is useful vs. manually specifying the parser for each test. Any additional details would be helpful.

**Comment by Cellule** [comment]
I see, well I want to be able to test my plugin with the default parser and `babel-eslint`. Also, I wanted to run the full ESLint test suite with `babel-eslint` to know which rule cause problem and why.
I managed to do it by hardcoding locally my solution in eslint project.
If you want, you can see the result of that analysis here https://github.com/babel/babel-eslint/issues/62.

It might be just  a one time thing, but I figured it doesn't cost much to support it and it would allow running the same test I did in the future to make sure multiple parser follow the same spec with regard to eslint.

**Comment by nzakas** [comment]
Thanks for explaining. I don't want to add something just to support a one-time thing, so it needs to make sense long term as well. I need to look a little bit closer at how this would make sense to do.

**Comment by ilyavolodin** [comment]
I think that would be useful for anyone trying to get their parser to support eslint. babel-eslint and esprima could probably use this for regression testing. I'm not really sure though how it helps eslint itself though.

**Comment by nzakas** [comment]
Yeah, I think it's useful, just want to make sure we think through it. For instance, if the goal is to run all ESLint tests with a different parser, then we need something that affects all tests, not just ones in a particular file.

**Comment by Cellule** [comment]
I did manage to run all the ESLint test suite with babel-eslint, however, I had to manually require eslint-tester and change the parser before any test ran. It wasn't that complicated, but there might be a better way to do it.
