### ISSUE TITLE
Unable to change schema definitions in ESLint

### ISSUE THREAD

**Issue by jrvidal** [eslint/eslint-tester#28]
Example: get a fresh clone of ESLint, and change some rule option keyword. For example, change `"as-needed"` in `quote-props` to `"as-needed-test"` in both `lib/rules/quote-props.js` (including the schema definition) and `tests/lib/rules/quote-props.js`. Run the tests.

Expected result: all test should pass since we're only renaming an option.

Result:
```
  5100 passing (24s)
  14 failing

  1) quote-props ({ a: 0, b(){} }):
     Error: eslint-tester:
    Configuration for rule "quote-props" is invalid:
    Value "as-needed-test" must be an enum value.

      at Array.forEach (native)

  2) quote-props ({ a: 0, b: 0 }):
     Error: eslint-tester:
    Configuration for rule "quote-props" is invalid:
    Value "as-needed-test" must be an enum value.

      at Array.forEach (native)

  3) quote-props ({ a: 0, 0: 0 }):
     Error: eslint-tester:
    Configuration for rule "quote-props" is invalid:
    Value "as-needed-test" must be an enum value.

      at Array.forEach (native)

  4) quote-props ({ a: 0, true: 0 }):
     Error: eslint-tester:
    Configuration for rule "quote-props" is invalid:
    Value "as-needed-test" must be an enum value.

      at Array.forEach (native)


  # An so on...
```

I'm not sure whether I making some obvious mistake, but I think this is a bug. As far as I can see, it's caused by the two different references to the `eslint` object mentioned in #24.

**Comment by nzakas** [comment]
@btmills thoughts?

**Comment by btmills** [comment]
Looks to me like @jrvidal's diagnosis was correct that this is a symptom of #24, making this the first instance of what was until now a theoretical problem. I'd say close this in favor of #24, summarize it there, and figure out how to resolve the discrepancy.

**Comment by nzakas** [comment]
Sounds good. Closing in favor of #24.

**Comment by bgw** [comment]
I just ran into this and ended up spending an hour wondering why I was getting the error that I was (I should've caught this quicker because I've been tracking #24). If anyone is working on eslint, and finds themselves in need of a temporary workaround:

```sh
$ rm -rf node_modules/eslint-tester/node_modules/eslint
$ ln -s ../../../ node_modules/eslint-tester/node_modules/eslint
```
