### ISSUE TITLE
Cannot call method 'getRuleOptionsSchema' of undefined

### ISSUE THREAD

**Issue by wbyoung** [eslint/eslint-tester#31]
I'm getting this error whenever I try to run tests. It appears that `eslint` does not export a `validator`.

**Comment by nzakas** [comment]
Eslint-tester is now deprecated. Please see http://eslint.org/docs/user-guide/migrating-to-1.0.0

**Comment by wbyoung** [comment]
@nzakas thanks!

I was following [this page](http://eslint.org/docs/developer-guide/working-with-plugins) which appears to be a little out of date, then.

I'm really liking ESLint so far, so thanks for helping create it.

**Comment by nzakas** [comment]
Oops! We forgot to update that page. We'll be sure to get it fixed ASAP.
